# Generated by Django 3.1.6 on 2021-05-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nAddress',
            new_name='nAuthor',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nBreed',
            new_name='nCategory',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nDay',
            new_name='nSynopsis',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='npet',
            new_name='nTitle',
        ),
        migrations.AddField(
            model_name='item',
            name='ngender',
            field=models.TextField(default=''),
        ),
    ]
