# Generated by Django 3.1.6 on 2021-06-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nread', models.DateTimeField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='reader',
            new_name='NewReader',
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTitle', models.TextField(default='')),
                ('nAuthor', models.TextField(default='')),
                ('Category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='StoryList.category')),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.TextField(default='')),
                ('unfinished', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='StoryList.list')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='Condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='StoryList.stories'),
        ),
    ]
