# Generated by Django 3.1.6 on 2021-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryList', '0002_auto_20210616_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='nread',
            new_name='Newreader',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Gender',
            new_name='nAge',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='Name',
            new_name='nGender',
        ),
        migrations.AddField(
            model_name='reader',
            name='nName',
            field=models.TextField(default=''),
        ),
    ]
