# Generated by Django 3.1.6 on 2021-06-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryList', '0003_auto_20210626_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='NewReader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StoryList.reader'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Condition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StoryList.stories'),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='unfinished',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StoryList.list'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='Category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='StoryList.category'),
        ),
    ]
