# Generated by Django 3.1.6 on 2021-06-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryList', '0004_auto_20210627_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='NewReader',
            new_name='newreader',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='Condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='Category',
            new_name='category',
        ),
    ]
